set-option -g history-limit 50000
# set -g default-terminal "tmux-256color"  # 이거 없어도 default로 설정되어 있음.
# set -ga terminal-overrides ",xterm-256color*:Tc"  # 아래 terminal-features로 대체?

# nvim :checkhealth 권장
set-option -a terminal-features 'xterm-256color:RGB'
set-option -g focus-events on
set-option -sg escape-time 100  # 너무 줄이면 (10ms) tmux 켤때 문자들 나와서 쫌 올려둠.
