export PATH=$HOME/.local/bin:$PATH

# cuda toolkit
export PATH=/usr/local/cuda/bin:$PATH
export LD_LIBRARY_PATH=/usr/local/cuda/lib64:/usr/local/cuda/extras/CUPTI/lib64:$LD_LIBRARY_PATH
export CUDA_ROOT=/usr/local/cuda

# python path
export PYTHONPATH=./${PYTHONPATH:+:${PYTHONPATH}}

# opencv
export LD_LIBRARY_PATH=/usr/local/lib:$LD_LIBRARY_PATH

# turbovnc
export PATH=/opt/TurboVNC/bin:$PATH

# TensorRT
export PATH=~/Utils/TensorRT/bin:$PATH
export LD_LIBRARY_PATH=~/Utils/TensorRT/lib:$LD_LIBRARY_PATH

# Solectrix
export PATH=~/video-app/src/release:$PATH

# typer
export _TYPER_STANDARD_TRACEBACK=1

# python activate venv
source ~/Utils/python_venvs/base/bin/activate

# alias
alias vim='neovim'
alias tmux='tmux -2'
alias zip0='function _zip0() { cd "$1" && zip -r -0 "../$(basename $PWD).zip" . && cd -; }; _zip0'

# --- Jupytext → HTML 파이프라인 + 임시 ipynb 삭제 ---
jupyhtml () {
    if [[ -z "$1" ]]; then
        echo "Usage: jupyhtml <script.py>"
        return 1
    fi

    local script="$1"
    local nb="${script%.py}.ipynb"
    # local html="${script%.py}.html"

    jupytext --to notebook "$script" \
      && jupyter nbconvert --to html --execute --post serve --ServePostProcessor.open_in_browser=False "$nb" \
      && rm -f "$nb"
      # && google-chrome "$html"
}

# bash vi mode
set -o vi

# To solve DDP issue.
export NCCL_P2P_DISABLE=1

# Auto Pull my-linux-setting
GIT_CMD="git -C ${HOME}/Utils/my-linux-setting"
timeout 10 $GIT_CMD fetch
if [ $($GIT_CMD rev-parse HEAD) != $($GIT_CMD rev-parse @{u}) ]; then
    echo ""
    echo "New my-linux-setting detected."
    read -p "Pull new setting? (y/n)? " CONT
    if [ $CONT == "y" ]; then
        $GIT_CMD pull
    fi
fi
